Max Fish Level: 10
XP Needed per Level: 1000
Fish:
  Cod:
    Display Name: "&9&oA Crusty Cod"
    Base Damage: 1
    Damage per Level: 0.5
    Base Armor: 1
    Armor per Level: 1
    Enchantments: knockback
    Enchantment Upgrade Levels: 1, 5, 10
    Equip Effect: DAMAGE_RESISTANCE
    Equip Effect Upgrade Levels: 1, 3, 6, 9
    Use Effect Duration:
