Max Fish Level: 10
Base XP per Level: 1000
XP Multiplier: 1.5
Fish:
  Cod:
    Display Name: "&9&oA Crusty Cod"
    Base Damage: 1
    Additional Damage per Level: 0.5
    Base Armor: 1
    Additional Armor per Level: 1
    Enchantment: knockback
    Enchantment Upgrade Levels:
      - 1
      - 5
      - 10
    Equip Effect: DAMAGE_RESISTANCE
    Equip Effect Upgrade Levels:
      - 1
      - 3
      - 6
      - 9
    Use Effect: ABSORPTION
    Use Effect Upgrade Levels:
      - 4
      - 7
      - 10
    Use Effect Durations:
      4: 8
      5: 10
      6: 12
    Use Effect Cooldowns:
      4: 60
      8: 55
      9: 50
      10: 45

Display Name: "&9&oA Crusty Cod"
Levels:
  1:
    xp: 1000
    damage: 1
    armor: 1
    speed: 1
    enchantments:
      - knockback 1
      - fire_aspect 2
    equipEffects:
      - damage_resistance 1
    useEffects:
      - absorption 1
    useEffectDuration: 10
    useEffectCooldown: 60